function copia = conver_name(copia)

%FUNCION EMPLEADA PARA CORREGIR ERRORES EN LOS NOMBRES DE LOS MUNICIPIOS EN
%LA BASE DE DATOS

errores = {'CALI'; 'LÓPEZ'; 'EL PAUJIL'; 'MAGÜI'; 'CARTAGENA'; 'SOTARA'; 'GACHALA'; 'PURÍSIMA'; 'ANCUYÁ'; 'CERRO SAN ANTONIO'; 'MARIQUITA'; 'SANTAFÉ DE ANTIOQUIA'; 'ITAGUI'; 'CACHIRÁ'; 'ANZA'; 'CARMEN DEL DARIEN'; 'CUASPUD'; 'COLOSO'; 'SAN ANDRÉS SOTAVENTO'; 'SAN JUAN DE RÍO SECO'; 'GÜICÁN'; 'SABANAS DE SAN ANGEL'; 'CAQUEZA'; 'MOMPÓS'; 'CHAMEZA'; 'CARURU'; 'BELÉN DE LOS ANDAQUIES'; 'CONSACA'; 'CÚCUTA'; 'GAMBITA'; 'ENTRERRIOS'; 'TORIBIO'; 'SAN ANDRES DE TUMACO'; 'RÍO IRO'; 'EL PIÑON'; 'SONSON'; 'MACHETA'; 'CALARCA'; 'TURBANÁ'; 'UMBITA'; 'GUAYABAL DE SIQUIMA'; 'GAMEZA'; 'IQUIRA'; 'PIENDAMÓ'; 'ABREGO'; 'SAN VICENTE'; 'VILLA DE SAN DIEGO DE UBATE'; 'DON MATÍAS'; 'FOMEQUE'};
correcciones = {'SANTIAGO DE CALI'; 'LÓPEZ DE MICAY'; 'EL PAUJÍL'; 'MAGÜÍ'; 'CARTAGENA DE INDIAS'; 'SOTARÁ PAISPAMBA'; 'GACHALÁ'; 'PURÍSIMA DE LA CONCEPCIÓN'; 'ANCUYA'; 'CERRO DE SAN ANTONIO'; 'SAN SEBASTIÁN DE MARIQUITA'; 'SANTA FÉ DE ANTIOQUIA'; 'ITAGÜÍ'; 'CÁCHIRA'; 'ANZÁ'; 'CARMEN DEL DARIÉN'; 'CUASPUD CARLOSAMA'; 'COLOSÓ'; 'SAN ANDRÉS DE SOTAVENTO'; 'SAN JUAN DE RIOSECO'; 'GÜICÁN DE LA SIERRA'; 'SABANAS DE SAN ÁNGEL'; 'CÁQUEZA'; 'SANTA CRUZ DE MOMPOX'; 'CHÁMEZA'; 'CARURÚ'; 'BELÉN DE LOS ANDAQUÍES'; 'CONSACÁ'; 'SAN JOSÉ DE CÚCUTA'; 'GÁMBITA'; 'ENTRERRÍOS'; 'TORIBÍO'; 'SAN ANDRÉS DE TUMACO'; 'RÍO IRÓ'; 'EL PIÑÓN'; 'SONSÓN'; 'MACHETÁ'; 'CALARCÁ'; 'TURBANA'; 'ÚMBITA'; 'GUAYABAL DE SÍQUIMA'; 'GÁMEZA'; 'ÍQUIRA'; 'PIENDAMÓ - TUNÍA'; 'ÁBREGO'; 'SAN VICENTE FERRER'; 'VILLA DE SAN DIEGO DE UBATÉ'; 'DONMATÍAS'; 'FÓMEQUE'};
    for i = 1:length(errores)
    copia.MUNICIPIO(strcmp(copia.MUNICIPIO, errores{i})) = {correcciones{i}};
    end
end
